import "./globals.css"
import { Inter } from "next/font/google"
import { TaskProvider } from "@/context/TaskProvider"
import NavBar from "@/components/NavBar"
import { Toaster } from "react-hot-toast"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-900`}>
        <TaskProvider className="flex justify-center bg-gray-900">
          <NavBar />
          {children}
          <Toaster position="top-center" reverseOrder={true} />
        </TaskProvider>
      </body>
    </html>
  )
}
